//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public int Id { get; set; }
        public bool IsMultiUserChat { get; set; }
        public string PublicId { get; set; }
    
        public virtual Users_Groups Users_Groups { get; set; }
    }
}
